### ISSUE TITLE
Can this project compile schema automatically without command line?

### ISSUE THREAD

**Issue by ghost** [sequsoft/flatbuffers-maven-plugin#1]
Can the Maven plug-in directly compile schema files in the project to generate java code without using the flatc command? Because frequent schema changes may be troublesome during the development process

**Comment by mdaley** [comment]
Hi majngkang, that's basically what this plugin is intended to do.  You put the plugin into your project as described in the README.  When you first run a maven build, it will download and compile flatc for your computer's architecture.  It keeps flatc in a hidden directory `.flatbuffers` in your home directory and will only rebuild it if you change the version of flatbuffers you want to compile schemas with.

Then when you run a maven build, at the generate-sources phase it will compile your schema files - perhaps in `src/main/resources/schemas` - and place them in the `target/generated-sources` directory.

Whenever you update schema files, the generated sources will automatically be updated when you run a build.  No need to do anything yourself with flatc.

Hope that helps?  Please ask more questions if you need to....

**Comment by majngkang** [comment]
Hello, thank you very much. How should I run the plug-in every time I modify the schema file? Also, the source tag needs to specify an FBS file to generate. It seems a bit unfriendly. Can you let him automatically read all FBS files for compilation? How should plugintest be used?



马敬康 MaJingKang
177301271115@163.com
电话：17730127115
 
From: Matthew Daley
Date: 2020-04-09 17:45
To: sequsoft/flatbuffers-maven-plugin
CC: majngkang; Author
Subject: Re: [sequsoft/flatbuffers-maven-plugin] Can this project compile schema automatically without command line? (#1)
Hi majngkang, that's basically what this plugin is intended to do. You put the plugin into your project as described in the README. When you first run a maven build, it will download and compile flatc for your computer's architecture. It keeps flatc in a hidden directory .flatbuffers in your home directory and will only rebuild it if you change the version of flatbuffers you want to compile schemas with.
Then when you run a maven build, at the generate-sources phase it will compile your schema files - perhaps in src/main/resources/schemas - and place them in the target/generated-sources directory.
Whenever you update schema files, the generated sources will automatically be updated when you run a build. No need to do anything yourself with flatc.
Hope that helps? Please ask more questions if you need to....

**Comment by ghost** [comment]
Hello, thank you very much. How should I run the plug-in every time I modify the schema file? Also, the source tag needs to specify an FBS file to generate. It seems a bit unfriendly. Can you let him automatically read all FBS files for compilation? How should plugintest be used?

**Comment by mdaley** [comment]
Hi, if you do `mvn generate-sources` on the command line it will regenerate the generated source files.  Also, if you are running a full build, e.g. `mvn clean package` or something like that, then the sources will be regenerated before the rest of the code is compiled.

If you are using Intellij, I guess you could create a configuration to run `mvn generate-sources` whenever you want it.

I can see what you mean about specifying a directory with all the schema files in.  I'll have a look at that once I get some time.  However, would it help you to set a `<source>` for each root object and then set an `<include>` for each directory that includes all of the other FBS files.  This worked for me - see the example I wrote in the README.

**Comment by ghost** [comment]
Hi Matthew Daley, thank you very much for your reply, but I have another question: java files can be generated through plug-ins. When we use them, it's more difficult to serialize and write offsets. Is there any way for programmers not to write those things, When serializing, we can directly build the byte array we want through flatbufferbuilder. When deserializing, we can also get the byte array directly?

**Comment by mdaley** [comment]
I'm not sure I understand the question.  However, I'll have a go at answering.

When you build a model of java objects into a flatbuffer you have to use the generated java code to put data into the flatbuffer, creating objects and their offsets, until, at the end, you write the root object, call `finish()` with the root object's offset, and the FlatBufferBuilder's `sizedByteArray()` method can be called to get the final `byte[]`.   

The serialised form of the data that you transfer around is the `byte[]`.

When you want to deserialise you have to `wrap()` the `byte[]` into a `ByteBuffer`.  Then you call the static method of the root object class with the buffer - `{RootClass}.getRootAs{RootClass}(buffer)` - and use code that you've written to extract all of the data back into your own model.

Of course, if you don't want to have your own Java object model, there's no need; you can just interrogate the data in the byte buffer directly using the methods in the generated classes.

I've fiddled around with testing out flatbuffers and I created a working example.  It shows how a Java object model can be turned into a flatbuffers model, serialised, deserialised and then turning back into the Java object model again.  I did this because I was interesting in understanding the difference between flatbuffers and protobuf which I currently work with.  The code is here in case it is useful to you:

https://github.com/mdaley/bufmark

What you want to look in is the flatbuffers module.

**Comment by ghost** [comment]
Thank you very much. I feel this code is very helpful to me!

**Comment by mdaley** [comment]
I'm very happy if the code has helped!  Would you be happy to close this issue now?
